# Generated by Django 3.2 on 2021-07-29 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0003_remove_exporttable_exporter_state'),
        ('advanced_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesteddownloadmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='requesteddownloadmodel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_downloads', to='core_module.tenant'),
        ),
    ]
