# Generated by Django 3.2 on 2021-08-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_module', '0001_initial'),
        ('advanced_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteddownloadmodel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_downloads', to='core_module.tenant'),
        ),
    ]
