# Generated by Django 3.2 on 2021-08-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_search', '0002_requesteddownloadmodel_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteddownloadmodel',
            name='remaining_search_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requesteddownloadmodel',
            name='request_type',
            field=models.CharField(blank=True, choices=[('search', 'search'), ('download', 'download')], max_length=20, null=True),
        ),
    ]
