# Generated by Django 3.2 on 2021-07-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporttable',
            name='EXCHANGE_RATE',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
