# Generated by Django 3.2 on 2021-08-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporttable',
            name='EXPORTER_PHONE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='IMPORTER_PHONE',
            field=models.TextField(blank=True, null=True),
        ),
    ]
