# Generated by Django 3.2 on 2021-07-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0002_alter_exporttable_exchange_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporttable',
            name='EXPORTER_STATE',
        ),
    ]
