# Generated by Django 3.2 on 2021-08-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0002_auto_20210825_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporttable',
            name='INVOICE_NO',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='INVOICE_NO',
            field=models.TextField(blank=True, null=True),
        ),
    ]
