# Generated by Django 3.2 on 2021-04-27 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0003_auto_20210428_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Country_master_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Country_master_owned_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Country_master_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CountryMaster',
            },
        ),
        migrations.CreateModel(
            name='CurrencyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Currency_master_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Currency_master_owned_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Currency_master_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='ImportTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('data_access_of_all_countries', models.TextField(blank=True, null=True)),
                ('workspace_shipment_limit', models.BigIntegerField(blank=True, null=True)),
                ('BE_DATE', models.DateTimeField(blank=True, null=True)),
                ('MONTH', models.CharField(blank=True, max_length=10, null=True)),
                ('YEAR', models.IntegerField(blank=True, null=True)),
                ('RITC', models.BigIntegerField(blank=True, null=True)),
                ('TWO_DIGIT', models.IntegerField(blank=True, null=True)),
                ('FOUR_DIGIT', models.IntegerField(blank=True, null=True)),
                ('RITC_DISCRIPTION', models.TextField(blank=True, null=True)),
                ('UQC', models.CharField(blank=True, max_length=5, null=True)),
                ('QUANTITY', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('UNT_PRICE_FC', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('INV_VALUE_FC', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('UNT_PRICE_INR', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('INV_NO', models.IntegerField(blank=True, null=True)),
                ('BE_NO', models.BigIntegerField(blank=True, null=True)),
                ('UNT_RATE_WITH_DUTY', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('PER_UNT_DUTY', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('DUTY_INR', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('DUTY_FC', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('DUTY_PERCENT', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('EX_TOTAL_VALUE', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('ASS_VALUE_INR', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('ASS_VALUE_USD', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('ASS_VALUE_FC', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('EXCHANGE_RATE', models.IntegerField(blank=True, null=True)),
                ('EXPORTER_NAME', models.CharField(blank=True, max_length=30, null=True)),
                ('EXPORTER_ADDRESS', models.TextField(blank=True, null=True)),
                ('PORT_OF_LOADING', models.CharField(blank=True, max_length=30, null=True)),
                ('PORT_OF_DISCHARGE', models.CharField(blank=True, max_length=30, null=True)),
                ('PORT_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('MODE_OF_PORT', models.CharField(blank=True, max_length=5, null=True)),
                ('IMPORTER_ID', models.CharField(blank=True, max_length=15, null=True)),
                ('IMPORTER_NAME', models.CharField(blank=True, max_length=40, null=True)),
                ('IMPORTER_ADDRESS', models.TextField(blank=True, null=True)),
                ('IMPORTER_CITY_STATE', models.CharField(blank=True, max_length=20, null=True)),
                ('IMPORTER_PIN', models.CharField(blank=True, max_length=10, null=True)),
                ('IMPORTER_PHONE', models.CharField(blank=True, max_length=15, null=True)),
                ('IMPORTER_EMAIL', models.CharField(blank=True, max_length=20, null=True)),
                ('IMPORTER_CONTACT_PERSON', models.CharField(blank=True, max_length=30, null=True)),
                ('BE_TYPE', models.CharField(blank=True, max_length=2, null=True)),
                ('CHA_NAME', models.CharField(blank=True, max_length=30, null=True)),
                ('Item_No', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('COUNTRY_OF_ORIGIN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_module.countrymaster')),
                ('CURRENCY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_module.currencymaster')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImportTable_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImportTable_owned_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImportTable_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ImportTable',
            },
        ),
    ]
