# Generated by Django 3.2 on 2021-08-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0004_transactionsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsmodel',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
