# Generated by Django 3.2 on 2021-04-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0004_countrymaster_currencymaster_importtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importtable',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='importtable',
            name='data_access_of_all_countries',
        ),
        migrations.RemoveField(
            model_name='importtable',
            name='name',
        ),
        migrations.RemoveField(
            model_name='importtable',
            name='workspace_shipment_limit',
        ),
        migrations.AlterField(
            model_name='importtable',
            name='CHA_NAME',
            field=models.TextField(blank=True, null=True),
        ),
    ]
