# Generated by Django 3.2 on 2021-04-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0005_auto_20210430_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtable',
            name='EXPORTER_NAME',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='IMPORTER_CONTACT_PERSON',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='PORT_OF_DISCHARGE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='PORT_OF_LOADING',
            field=models.TextField(blank=True, null=True),
        ),
    ]
