# Generated by Django 3.2 on 2021-08-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0006_userotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='user',
        ),
        migrations.AddField(
            model_name='userotp',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
