# Generated by Django 3.2 on 2021-04-30 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0007_auto_20210430_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencymaster',
            options={'verbose_name_plural': 'CurrencyMaster'},
        ),
        migrations.CreateModel(
            name='ExportTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SB_DATE', models.DateTimeField(blank=True, null=True)),
                ('MONTH', models.CharField(blank=True, max_length=10, null=True)),
                ('YEAR', models.IntegerField(blank=True, null=True)),
                ('RITC', models.BigIntegerField(blank=True, null=True)),
                ('TWO_DIGIT', models.IntegerField(blank=True, null=True)),
                ('FOUR_DIGIT', models.IntegerField(blank=True, null=True)),
                ('RITC_DISCRIPTION', models.TextField(blank=True, null=True)),
                ('UQC', models.CharField(blank=True, max_length=5, null=True)),
                ('QUANTITY', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('UNT_PRICE_FC', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('INV_VALUE_FC', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('UNT_PRICE_INR', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('INVOICE_NO', models.IntegerField(blank=True, null=True)),
                ('SB_NO', models.BigIntegerField(blank=True, null=True)),
                ('UNIT_RATE_WITH_FOB', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('PER_UNT_FOB', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('FOB_INR', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('FOB_FC', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('FOB_USD', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('EXCHANGE_RATE', models.IntegerField(blank=True, null=True)),
                ('IMPORTER_NAME', models.CharField(blank=True, max_length=40, null=True)),
                ('IMPORTER_ADDRESS', models.TextField(blank=True, null=True)),
                ('PORT_OF_LOADING', models.TextField(blank=True, null=True)),
                ('PORT_OF_DISCHARGE', models.TextField(blank=True, null=True)),
                ('PORT_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('MODE_OF_PORT', models.CharField(blank=True, max_length=5, null=True)),
                ('EXPORTER_ID', models.CharField(blank=True, max_length=15, null=True)),
                ('EXPORTER_NAME', models.TextField(blank=True, null=True)),
                ('EXPORTER_ADDRESS', models.TextField(blank=True, null=True)),
                ('EXPORTER_CITY', models.TextField(blank=True, null=True)),
                ('EXPORTER_STATE', models.TextField(blank=True, null=True)),
                ('EXPORTER_PIN', models.CharField(blank=True, max_length=10, null=True)),
                ('EXPORTER_PHONE', models.CharField(blank=True, max_length=15, null=True)),
                ('EXPORTER_EMAIL', models.TextField(blank=True, null=True)),
                ('EXPORTER_CONTACT_PERSON', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('COUNTRY_OF_ORIGIN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_module.countrymaster')),
                ('CURRENCY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_module.currencymaster')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExportTable_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExportTable_owned_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExportTable_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ExportTable',
            },
        ),
    ]
