# Generated by Django 3.2 on 2021-04-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0008_auto_20210430_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporttable',
            name='INVOICE_NO',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
