# Generated by Django 3.2 on 2021-05-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0009_alter_exporttable_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttable',
            name='COUNTRY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExportTable_COUNTRY', to='core_module.countrymaster'),
        ),
        migrations.AddField(
            model_name='importtable',
            name='COUNTRY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImportTable_COUNTRY', to='core_module.countrymaster'),
        ),
    ]
