# Generated by Django 3.2 on 2021-05-11 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0011_companymaster_productmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='ProductID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_module.productmaster'),
        ),
    ]
