# Generated by Django 3.2 on 2021-05-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0012_alter_productmaster_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymaster',
            name='location',
        ),
        migrations.RemoveField(
            model_name='companymaster',
            name='owned_by',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='ProductID',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='owned_by',
        ),
    ]
