# Generated by Django 3.2 on 2021-05-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0013_auto_20210518_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymaster',
            name='location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
