# Generated by Django 3.2 on 2021-05-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0014_auto_20210518_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
