# Generated by Django 3.2 on 2021-05-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0015_alter_profile_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplans',
            old_name='tenant_id',
            new_name='tenant',
        ),
    ]
