# Generated by Django 3.2 on 2021-05-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0016_rename_tenant_id_userplans_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymaster',
            name='owned_by',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='ProductID',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='owned_by',
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
