# Generated by Django 3.2 on 2021-05-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0017_auto_20210519_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrymaster',
            name='location',
        ),
        migrations.RemoveField(
            model_name='countrymaster',
            name='owned_by',
        ),
        migrations.RemoveField(
            model_name='exporttable',
            name='owned_by',
        ),
        migrations.RemoveField(
            model_name='importtable',
            name='owned_by',
        ),
        migrations.AlterField(
            model_name='exporttable',
            name='COUNTRY_OF_ORIGIN',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exporttable',
            name='CURRENCY',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='COUNTRY_OF_ORIGIN',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='CURRENCY',
            field=models.TextField(blank=True, null=True),
        ),
    ]
