# Generated by Django 3.2 on 2021-05-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0018_auto_20210519_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporttable',
            name='EXPORTER_ID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exporttable',
            name='EXPORTER_PHONE',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='exporttable',
            name='EXPORTER_PIN',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='exporttable',
            name='IMPORTER_NAME',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exporttable',
            name='MODE_OF_PORT',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='exporttable',
            name='PORT_CODE',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='exporttable',
            name='UQC',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='BE_TYPE',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='IMPORTER_ID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='IMPORTER_NAME',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='IMPORTER_PHONE',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='IMPORTER_PIN',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='MODE_OF_PORT',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='PORT_CODE',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='UQC',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
