# Generated by Django 3.2 on 2021-05-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0019_auto_20210519_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='iec_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
