# Generated by Django 3.2 on 2021-05-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0020_auto_20210519_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporttable',
            name='FOUR_DIGIT',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exporttable',
            name='RITC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exporttable',
            name='TWO_DIGIT',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='FOUR_DIGIT',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='RITC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importtable',
            name='TWO_DIGIT',
            field=models.TextField(blank=True, null=True),
        ),
    ]
