# Generated by Django 3.2 on 2021-05-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0022_filterdatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterdatamodel',
            name='total_count',
            field=models.JSONField(default=dict),
        ),
    ]
