# Generated by Django 3.2 on 2021-05-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0024_filterdatamodel_workspace_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterdatamodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
