# Generated by Django 3.2 on 2021-05-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0025_filterdatamodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttable',
            name='commodity_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
