# Generated by Django 3.2 on 2021-06-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0026_exporttable_commodity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='hs_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
