# Generated by Django 3.2 on 2021-06-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0027_alter_productmaster_hs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='digits',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
