# Generated by Django 3.2 on 2021-06-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0028_productmaster_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='hs_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
