# Generated by Django 3.2 on 2021-06-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0030_importtable_commodity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtable',
            name='importer_value_fc',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='importtable',
            name='importer_value_inr',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='importtable',
            name='importer_value_usd',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True),
        ),
    ]
