# Generated by Django 3.2 on 2021-06-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0031_auto_20210610_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtable',
            name='DUTY_USD',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
    ]
