# Generated by Django 3.2 on 2021-06-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0032_importtable_duty_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtable',
            name='EXCHANGE_RATE',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
