# Generated by Django 3.2 on 2021-06-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0033_alter_importtable_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtable',
            name='Item_No',
            field=models.TextField(blank=True, null=True),
        ),
    ]
